Repository DogUin-Community/doguin, pull requests merged in 2024-11, with the labels that each got.

#184 feature. 마이페이지 조회 기능에 로컬캐시(Ehcache) 적용
  src/main/java/com/sparta/doguin/domain/mypage/controller/MypageController.java
  src/main/java/com/sparta/doguin/domain/mypage/dto/MypageResponse.java
  src/main/java/com/sparta/doguin/domain/mypage/service/MypageService.java
  src/main/resources/ehcache.xml
Labels: enhancement

#188 MypageServiceTest 코드 수정
  src/test/java/com/sparta/doguin/domain/mypage/service/MypageServiceTest.java
Labels: test, fix

#203 fix. 마이페이지 조회 테스트 코드 수정
  src/test/java/com/sparta/doguin/domain/mypage/service/MypageServiceTest.java
  src/test/java/com/sparta/doguin/domain/test/InfoCreateTest.java
  src/test/java/com/sparta/doguin/domain/test/QueryTest.java
Labels: test, fix

#238 refactor. 하나의 공고에 대해 여러명이 신청을 눌렀을 경우에 대해 정확한 동시성 제어 처리와 높은 응답속도로 개선 완료
  gradlew
  src/main/java/com/sparta/doguin/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/sparta/doguin/domain/matching/controller/MathchingController.java
  src/main/java/com/sparta/doguin/domain/matching/repository/MatchingRepository.java
  src/main/java/com/sparta/doguin/domain/matching/service/MatchingService.java
  src/main/java/com/sparta/doguin/domain/matching/service/MatchingServiceImpl.java
  src/main/java/com/sparta/doguin/domain/test/TestController.java
  src/main/java/com/sparta/doguin/security/AuthUser.java
  src/test/java/com/sparta/doguin/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/sparta/doguin/domain/matching/service/MatchingServiceImplTest.java
  src/test/java/com/sparta/doguin/domain/setup/DataUtil.java
  src/test/java/com/sparta/doguin/domain/test/dumyData.java
Labels: refactor

#248 refactor. 회원가입 시 닉네임 중복 체크
  src/main/java/com/sparta/doguin/domain/common/response/ApiResponseUserEnum.java
  src/main/java/com/sparta/doguin/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/doguin/domain/user/service/AuthService.java
Labels: enhancement, refactor

#251 refactor. 빈칸 삭제
  src/main/java/com/sparta/doguin/domain/follow/entity/Follow.java
Labels: refactor

#263 refactor. AuthService 로그로 수정
  src/main/java/com/sparta/doguin/domain/user/service/AuthService.java
Labels: refactor

#282 fix. AuthServiceTest 코드 수정
  src/test/java/com/sparta/doguin/domain/user/service/AuthServiceTest.java
Labels: fix

#283 fix. AuthServiceTest 테스트 코드 수정
  src/test/java/com/sparta/doguin/domain/user/service/AuthServiceTest.java
Labels: fix
