Repository DogUin-Community/doguin, pull requests merged in 2024-10, with the labels that each got.

#82 add. 채팅 기능 구현 추가
  build.gradle
  src/main/java/com/sparta/doguin/config/RedisConfig.java
  src/main/java/com/sparta/doguin/config/WebSocketAuthInterceptor.java
  src/main/java/com/sparta/doguin/config/WebSocketConfig.java
  src/main/java/com/sparta/doguin/domain/chatting/controller/ChatController.java
  src/main/java/com/sparta/doguin/domain/chatting/dto/ChatRequest.java
  src/main/java/com/sparta/doguin/domain/chatting/dto/ChatResponse.java
  src/main/java/com/sparta/doguin/domain/chatting/entity/ChatRoom.java
  src/main/java/com/sparta/doguin/domain/chatting/entity/Message.java
  src/main/java/com/sparta/doguin/domain/chatting/entity/UserChatRoom.java
  src/main/java/com/sparta/doguin/domain/chatting/repository/ChatRoomRepository.java
  src/main/java/com/sparta/doguin/domain/chatting/repository/MessageRepository.java
  src/main/java/com/sparta/doguin/domain/chatting/repository/UserChatRoomRepository.java
  src/main/java/com/sparta/doguin/domain/chatting/service/ChatService.java
  src/main/java/com/sparta/doguin/domain/common/exception/ChatException.java
  src/main/java/com/sparta/doguin/domain/common/response/ApiResponseChatEnum.java
Labels: enhancement

#123 refactor. AuthService 회원가입 JwtUtilRequest 적용하여 직관적으로 코드 리팩토링
  src/main/java/com/sparta/doguin/config/security/JwtUtil.java
  src/main/java/com/sparta/doguin/config/security/dto/JwtUtilRequest.java
  src/main/java/com/sparta/doguin/domain/user/service/AuthService.java
Labels: refactor

#126 fix. 로그인 시 토큰 생성 후 Bearer 접두사 제거한 순수한 토큰을 헤더로 응답받기 위해 코드 수정
  src/main/java/com/sparta/doguin/config/security/JwtSecurityFilter.java
  src/main/java/com/sparta/doguin/config/security/JwtUtil.java
  src/main/java/com/sparta/doguin/domain/follow/controller/FollowController.java
  src/main/java/com/sparta/doguin/domain/user/controller/AuthController.java
  src/main/java/com/sparta/doguin/domain/user/service/AuthService.java
Labels: refactor

#151 test. 유저, 팔로우, 마이페이지 서비스로직 테스트코드
  src/main/java/com/sparta/doguin/domain/mypage/service/MypageService.java
  src/test/java/com/sparta/doguin/domain/follow/service/FollowServiceTest.java
  src/test/java/com/sparta/doguin/domain/mypage/service/MypageServiceTest.java
  src/test/java/com/sparta/doguin/domain/setup/DataUtil.java
  src/test/java/com/sparta/doguin/domain/user/service/AuthServiceTest.java
  src/test/java/com/sparta/doguin/domain/user/service/UserServiceTest.java
Labels: test

#153 update. 회원가입 시 프로필 S3 연동
  src/main/java/com/sparta/doguin/domain/user/controller/AuthController.java
  src/main/java/com/sparta/doguin/domain/user/service/AuthService.java
Labels: enhancement

#156 fix. 회원가입 시 프로필 S3 연동 후 테스트 코드 수정
  src/test/java/com/sparta/doguin/domain/user/service/AuthServiceTest.java
  src/test/java/com/sparta/doguin/domain/user/service/UserServiceTest.java
Labels: test, fix

#174 소셜로그인 구현 완료
  build.gradle
  src/main/java/com/sparta/doguin/config/SocialLoginConfig.java
  src/main/java/com/sparta/doguin/domain/common/response/ApiResponseUserEnum.java
  src/main/java/com/sparta/doguin/domain/user/controller/AuthController.java
  src/main/java/com/sparta/doguin/domain/user/entity/User.java
  src/main/java/com/sparta/doguin/domain/user/enums/UserGrade.java
  src/main/java/com/sparta/doguin/domain/user/enums/UserRole.java
  src/main/java/com/sparta/doguin/domain/user/service/AuthService.java
  src/main/java/com/sparta/doguin/domain/user/service/SocialLoginService.java
  src/main/java/com/sparta/doguin/security/JwtAuthenticationToken.java
  src/main/java/com/sparta/doguin/security/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/sparta/doguin/domain/user/service/SocialLoginServiceTest.java
Labels: enhancement
